server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name _;
    root /var/www/html;
    index user_upload.php;

    client_max_body_size 100M;
    client_header_buffer_size 128k;
    large_client_header_buffers 4 128k;

    location / {
        try_files $uri $uri/ /user_upload.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
